version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-service
    ports:
      - "8000:8000"
    restart: always

  flask:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    container_name: flask-service
    ports:
      - "5000:5000"
    depends_on:
      - fastapi
    restart: always
